### ISSUE TITLE
pod has unfinished line

### ISSUE THREAD

**Issue by jonassmedegaard** [smithfarm/cell#3]
Pod for App::CELL::Status (or at least its rendering at MetaCPAN) contains an unfinished sentence:

> new
> 
> Construct a status object and trigger a log message if the level is anything other than "OK". Always returns a status object. If no level is specified, the level will be 'ERR'. If no code is given, the code will be

**Comment by jonassmedegaard** [comment]
looks like an extra "be" crept into the text now :-/

**Comment by smithfarm** [comment]
@jonassmedegaard Thanks - fixed.
